In [1]:
import pandas as pd

print("done")

done

In [2]:
df1 = pd.read_csv(r"C:\Users\Muskan\Desktop\DAproject\sales_teams.csv")
df2= pd.read_csv(r"C:\Users\Muskan\Desktop\DAproject\sales_pipeline.csv")
df3= pd.read_csv(r"C:\Users\Muskan\Desktop\DAproject\products.csv")
df4 = pd.read_csv(r"C:\Users\Muskan\Desktop\DAproject\accounts.csv")

In [3]:
df1.describe()

          sales_agent        manager regional_office
count              35             35              35
unique             35              6               3
top     Anna Snelling  Melvin Marxen            East
freq                1              6              12

In [6]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sales_agent      35 non-null     object
 1   manager          35 non-null     object
 2   regional_office  35 non-null     object
dtypes: object(3)
memory usage: 972.0+ bytes

In [7]:
df1.isnull().sum()

sales_agent        0
manager            0
regional_office    0
dtype: int64

In [8]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8800 entries, 0 to 8799
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   opportunity_id  8800 non-null   object
 1   sales_agent     8800 non-null   object
 2   product         8800 non-null   object
 3   account         7375 non-null   object
 4   deal_stage      8800 non-null   object
 5   engage_date     8300 non-null   object
 6   close_date      6711 non-null   object
 7   close_value     6711 non-null   float64
dtypes: float64(1), object(7)
memory usage: 550.1+ KB

In [9]:
df2.dtypes

opportunity_id     object
sales_agent        object
product            object
account            object
deal_stage         object
engage_date        object
close_date         object
close_value       float64
dtype: object

In [10]:
df2['close_date']=pd.to_datetime(df2['close_date'])
df2['engage_date']=pd.to_datetime(df2['engage_date'])
df2.dtypes

opportunity_id            object
sales_agent               object
product                   object
account                   object
deal_stage                object
engage_date       datetime64[ns]
close_date        datetime64[ns]
close_value              float64
dtype: object

In [11]:
df2.isnull().sum()

opportunity_id       0
sales_agent          0
product              0
account           1425
deal_stage           0
engage_date        500
close_date        2089
close_value       2089
dtype: int64

In [68]:
df2['account'] = df2['account'].fillna("Unknown Account")

In [69]:
df2['close_value'] = df2['close_value'].fillna(0)

In [70]:
df2.isnull().sum()

opportunity_id       0
sales_agent          0
product              0
account              0
deal_stage           0
engage_date        500
close_date        2089
close_value          0
dtype: int64

In [14]:
df3

          product series  sales_price
0       GTX Basic    GTX          550
1         GTX Pro    GTX         4821
2      MG Special     MG           55
3     MG Advanced     MG         3393
4    GTX Plus Pro    GTX         5482
5  GTX Plus Basic    GTX         1096
6         GTK 500    GTK        26768

In [15]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   product      7 non-null      object
 1   series       7 non-null      object
 2   sales_price  7 non-null      int64
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

In [16]:
df4

,account,sector,year_established,revenue,employees,office_location,subsidiary_of
0,Acme Corporation,technolgy,1996,1100.04,2822,United States,NaN
1,Betasoloin,medical,1999,251.41,495,United States,NaN
2,Betatech,medical,1986,647.18,1185,Kenya,NaN
3,Bioholding,medical,2012,587.34,1356,Philipines,NaN
4,Bioplex,medical,1991,326.82,1016,United States,NaN
...,...,...,...,...,...,...,...
80,Zathunicon,retail,2010,71.12,144,United States,NaN
81,Zencorporation,technolgy,2011,40.79,142,China,NaN
82,Zoomit,entertainment,1992,324.19,978,United States,NaN
83,Zotware,software,1979,4478.47,13809,United States,NaN
84,Zumgoity,medical,1984,441.08,1210,United States,NaN

In [49]:
df4['year_established'] = df4['year_established'].astype(int)

In [50]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   account           85 non-null     object
 1   sector            85 non-null     object
 2   year_established  85 non-null     int64
 3   revenue           85 non-null     float64
 4   employees         85 non-null     int64
 5   office_location   85 non-null     object
 6   subsidiary_of     15 non-null     object
dtypes: float64(1), int64(2), object(4)
memory usage: 4.8+ KB

In [51]:
df4.isnull().sum()

account              0
sector               0
year_established     0
revenue              0
employees            0
office_location      0
subsidiary_of       70
dtype: int64

In [63]:
df4['subsidiary_of'] = df4['subsidiary_of'].fillna('Independent')

In [64]:
df4

,account,sector,year_established,revenue,employees,office_location,subsidiary_of
0,Acme Corporation,technolgy,1996,1100.04,2822,United States,Independent
1,Betasoloin,medical,1999,251.41,495,United States,Independent
2,Betatech,medical,1986,647.18,1185,Kenya,Independent
3,Bioholding,medical,2012,587.34,1356,Philipines,Independent
4,Bioplex,medical,1991,326.82,1016,United States,Independent
...,...,...,...,...,...,...,...
80,Zathunicon,retail,2010,71.12,144,United States,Independent
81,Zencorporation,technolgy,2011,40.79,142,China,Independent
82,Zoomit,entertainment,1992,324.19,978,United States,Independent
83,Zotware,software,1979,4478.47,13809,United States,Independent
84,Zumgoity,medical,1984,441.08,1210,United States,Independent

In [65]:
!pip install pymysql
print("done")

Requirement already satisfied: pymysql in c:\users\muskan\anaconda3\lib\site-packages (1.1.2)
done

In [71]:
import warnings
import datetime
warnings.filterwarnings('ignore')

from sqlalchemy import  create_engine

import pandas as pd

engine = create_engine("mysql+pymysql://root:root@127.0.0.1:3306/crm_sales")

# {root}:{password}@host:port/{database name}

#Establish a connection

conn = engine.connect()


#Write DataFrame to a SQL table

df1.to_sql('sales_team', engine, index=False, if_exists='replace')
df2.to_sql('sales_pipeline', engine, index=False, if_exists='replace')
df3.to_sql('products', engine, index=False, if_exists='replace')
df4.to_sql('accounts', engine, index=False, if_exists='replace')

#Close Connection
conn.close()
print("done")

done

In [67]:
df4

,account,sector,year_established,revenue,employees,office_location,subsidiary_of
0,Acme Corporation,technolgy,1996,1100.04,2822,United States,Independent
1,Betasoloin,medical,1999,251.41,495,United States,Independent
2,Betatech,medical,1986,647.18,1185,Kenya,Independent
3,Bioholding,medical,2012,587.34,1356,Philipines,Independent
4,Bioplex,medical,1991,326.82,1016,United States,Independent
...,...,...,...,...,...,...,...
80,Zathunicon,retail,2010,71.12,144,United States,Independent
81,Zencorporation,technolgy,2011,40.79,142,China,Independent
82,Zoomit,entertainment,1992,324.19,978,United States,Independent
83,Zotware,software,1979,4478.47,13809,United States,Independent
84,Zumgoity,medical,1984,441.08,1210,United States,Independent